var $=jQuery.noConflict();$(document).ready(function($){"use strict";var submitContact=$('#submit_contact'),message=$('#msg');submitContact.on('click',function(e){e.preventDefault();var $this=$(this);$.ajax({type:"POST",url:'contact.php',dataType:'json',cache:!1,data:$('#contact-form').serialize(),success:function(data){if(data.info!=='error'){$this.parents('form').find('input[type=text],textarea,select').filter(':visible').val('');message.hide().removeClass('success').removeClass('error').addClass('success').html(data.msg).fadeIn('slow').delay(5000).fadeOut('slow')}else{message.hide().removeClass('success').removeClass('error').addClass('error').html(data.msg).fadeIn('slow').delay(5000).fadeOut('slow')}}})})})
if(jQuery(".owl-carousel.videos_slider_wrapper").length>0){jQuery(document).ready(function(){"use strict";var owl_videos=jQuery(".owl-carousel.videos_slider_wrapper");owl_videos.on('initialized.owl.carousel',function(e){jQuery(".owl-item.active").eq(1).addClass('current-video')});owl_videos.owlCarousel({loop:!0,margin:30,responsiveClass:!0,items:3,responsive:{0:{items:1,nav:!0},600:{items:3,nav:!1},1000:{items:3,nav:!0,loop:!0}},navText:["<i class='fa fa-arrow-circle-o-left'></i>","<i class='fa fa-arrow-circle-o-right'></i>"],autoplay:!1,autoplayHoverPause:!0});owl_videos.on('translated.owl.carousel',function(e){jQuery(".owl-item").removeClass('current-video');jQuery(".owl-item.active").eq(1).addClass('current-video')})})}
function easyCharts(){"use strict";jQuery('.easyPieChart').each(function(){var $this,$parent_width,$chart_size;$this=jQuery(this);$parent_width=jQuery(this).parent().width();jQuery(this).css('height',$parent_width+'px');$chart_size=$this.attr('data-barSize');if(!$this.hasClass('chart-animated')){$this.easyPieChart({animate:3000,lineCap:'round',lineWidth:$this.attr('data-lineWidth'),barColor:$this.attr('data-barColor'),trackColor:$this.attr('data-trackColor'),scaleColor:'transparent',size:$parent_width,onStep:function(from,to,percent){jQuery(this.el).find('.chart-percent span').text(Math.round(percent))}})}})}
jQuery(document).ready(function(){easyCharts()});if(jQuery("#trigger-overlay").length>0){(function(){var triggerBttn=document.getElementById('trigger-overlay'),overlay=document.querySelector('div.overlay'),closeBttn=overlay.querySelector('.overlay-close');transEndEventNames={'WebkitTransition':'webkitTransitionEnd','MozTransition':'transitionend','OTransition':'oTransitionEnd','msTransition':'MSTransitionEnd','transition':'transitionend'},transEndEventName=transEndEventNames[Modernizr.prefixed('transition')],support={transitions:Modernizr.csstransitions};function toggleOverlay(){if(classie.has(overlay,'open')){classie.remove(overlay,'open');classie.add(overlay,'close');var onEndTransitionFn=function(ev){if(support.transitions){if(ev.propertyName!=='visibility')return;this.removeEventListener(transEndEventName,onEndTransitionFn)}
classie.remove(overlay,'close')};if(support.transitions){overlay.addEventListener(transEndEventName,onEndTransitionFn)}
else{onEndTransitionFn()}}
else if(!classie.has(overlay,'close')){classie.add(overlay,'open')}}
triggerBttn.addEventListener('click',toggleOverlay);closeBttn.addEventListener('click',toggleOverlay)})()}
if(jQuery("#trigger-overlay-sticky").length>0){"use strict";(function(){var triggerBttn=document.getElementById('trigger-overlay-sticky'),overlay=document.querySelector('div.overlay'),closeBttn=overlay.querySelector('.overlay-close');transEndEventNames={'WebkitTransition':'webkitTransitionEnd','MozTransition':'transitionend','OTransition':'oTransitionEnd','msTransition':'MSTransitionEnd','transition':'transitionend'},transEndEventName=transEndEventNames[Modernizr.prefixed('transition')],support={transitions:Modernizr.csstransitions};function toggleOverlay(){if(classie.has(overlay,'open')){classie.remove(overlay,'open');classie.add(overlay,'close');var onEndTransitionFn=function(ev){if(support.transitions){if(ev.propertyName!=='visibility')return;this.removeEventListener(transEndEventName,onEndTransitionFn)}
classie.remove(overlay,'close')};if(support.transitions){overlay.addEventListener(transEndEventName,onEndTransitionFn)}
else{onEndTransitionFn()}}
else if(!classie.has(overlay,'close')){classie.add(overlay,'open')}}
triggerBttn.addEventListener('click',toggleOverlay);closeBttn.addEventListener('click',toggleOverlay)})()}
if(jQuery(".pego-isotope-wrapper").length>0){jQuery(document).ready(function(){"use strict";jQuery(function(){var container=jQuery(".pego-isotope-wrapper");container.isotope({itemSelector:".isotope-item",layoutMode:"masonry",transitionDuration:"0.7s"});var optionSets=jQuery(".option-set"),optionLinks=optionSets.find("a");optionLinks.on('click',function(){var $this=jQuery(this);if($this.hasClass("selected")){return!1}
var optionSet=$this.parents(".option-set");optionSet.find(".selected").removeClass("selected");$this.addClass("selected");var options={},key=optionSet.attr("data-option-key"),value=$this.attr("data-option-value");value=value==="false"?!1:value;options[key]=value;if(key==="layoutMode"&&typeof changeLayoutMode==="function"){changeLayoutMode($this,options)}else{container.isotope(options)}
return!1})})});(function($,sr){var debounce=function(func,threshold,execAsap){var timeout;return function debounced(){var obj=this,args=arguments;function delayed(){if(!execAsap)
func.apply(obj,args);timeout=null};if(timeout)
clearTimeout(timeout);else if(execAsap)
func.apply(obj,args);timeout=setTimeout(delayed,threshold||100)}}
jQuery.fn[sr]=function(fn){return fn?this.on('resize',debounce(fn)):this.trigger(sr)}})(jQuery,'smartresize');jQuery(window).smartresize(function(){"use strict";var container=jQuery(".pego-isotope-wrapper");container.isotope({itemSelector:".isotope-item",layoutMode:"masonry",transitionDuration:"0.7s"})})}
if(jQuery(".pego-isotope-wrapper-type2").length>0){jQuery(document).ready(function(){"use strict";jQuery(function(){var container=jQuery(".pego-isotope-wrapper-type2");container.isotope({itemSelector:".portfolio-items-single-type2",transitionDuration:"0.7s",layoutMode:"masonry",percentPosition:!0,columnWidth:'.portfolio-items-single-type2-sizer'});var optionSets=jQuery(".option-set"),optionLinks=optionSets.find("a");optionLinks.on('click',function(){var $this=jQuery(this);if($this.hasClass("selected")){return!1}
var optionSet=$this.parents(".option-set");optionSet.find(".selected").removeClass("selected");$this.addClass("selected");var options={},key=optionSet.attr("data-option-key"),value=$this.attr("data-option-value");value=value==="false"?!1:value;options[key]=value;if(key==="layoutMode"&&typeof changeLayoutMode==="function"){changeLayoutMode($this,options)}else{container.isotope(options)}
return!1})})});(function($,sr){var debounce=function(func,threshold,execAsap){var timeout;return function debounced(){var obj=this,args=arguments;function delayed(){if(!execAsap)
func.apply(obj,args);timeout=null};if(timeout)
clearTimeout(timeout);else if(execAsap)
func.apply(obj,args);timeout=setTimeout(delayed,threshold||100)}}
jQuery.fn[sr]=function(fn){return fn?this.on('resize',debounce(fn)):this.trigger(sr)}})(jQuery,'smartresize');jQuery(window).smartresize(function(){var container=jQuery(".pego-isotope-wrapper-type2");container.isotope({itemSelector:".portfolio-items-single-type2",transitionDuration:"0.7s",layoutMode:"masonry",percentPosition:!0,columnWidth:'.portfolio-items-single-type2-sizer'})})}
jQuery(function(){"use strict";jQuery('.main-menu .sf-menu').superfish({delay:300,animation:{opacity:'show',height:'show'},speed:'fast',autoArrows:!0,dropShadows:!1})});(function($,sr){var debounce=function(func,threshold,execAsap){var timeout;return function debounced(){var obj=this,args=arguments;function delayed(){if(!execAsap)
func.apply(obj,args);timeout=null};if(timeout)
clearTimeout(timeout);else if(execAsap)
func.apply(obj,args);timeout=setTimeout(delayed,threshold||100)}}
jQuery.fn[sr]=function(fn){return fn?this.on('resize',debounce(fn)):this.trigger(sr)}})(jQuery,'smartresize')